module.exports = {
	'APPLICATION_ID' 	: 	'Edxfur3DzyAH9oWZweIBUo1cx9JsgTjGgDgm1qSB',
	'JAVASCRIPT_KEY'	: 	'TA9moODSZOCZxmkMfvxN1HuPYiDn6Q42ZSAnH27I',
	'MASTER_KEY'		: 	'CFET5YB86KgNRXDRTNGMj76o4wuwCsXUAjydrALQ'
}